//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opama.EMailTemplates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerificationEmail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerificationEmail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opama.EMailTemplates.VerificationEmail", typeof(VerificationEmail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;%NAME%&gt;,&lt;br&gt;&lt;br&gt;
        ///You&apos;ve signed up for safe password storage. Awesome!&lt;br&gt;&lt;br&gt;
        ///Please &lt;a href=&quot;https://&lt;%HOST%&gt;/app/verify?guid=&lt;%GUID%&gt;&quot;&gt;verify your e-mail address&lt;/a&gt; to start using your Opama powered safe password storage.
        ///&lt;br /&gt;&lt;br /&gt;
        ///If the link doesn&apos;t work, copy the next line and paste it in your favorite browser.
        ///&lt;br /&gt;&lt;br /&gt;
        ///https://&lt;%HOST%&gt;/app/verify?guid=&lt;%GUID%&gt;
        ///&lt;br /&gt;&lt;br /&gt;
        ///Safe browsing!
        ///&lt;br /&gt;
        ///- Opama&lt;br /&gt;&lt;br /&gt;
        ///P.S. If you didn&apos;t request an account, &lt;a href=&quot;https://&lt;%HOST%&gt;/app/nosignu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLBody {
            get {
                return ResourceManager.GetString("HTMLBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your signup with the Opama powered secure password storage..
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi &lt;%NAME%&gt;,
        ///
        ///You&apos;ve signed up for safe password storage. Awesome!
        ///
        ///Please verify your e-mail address to start using your Opama powered safe password storage by clicking the link below. If the link doesn&apos;t work, copy and paste it in your favorite browser.
        ///
        ///https://&lt;%HOST%&gt;/app/verify?guid=&lt;%GUID%&gt;
        ///
        ///Safe browsing! 
        /// - Opama
        ///
        ///P.S. If you didn&apos;t request an account, let us know by clicking (or copy &apos;n pasting) the link below.
        ///https://&lt;%HOST%&gt;/app/nosignup?guid=&lt;%GUID%&gt;
        ///.
        /// </summary>
        internal static string TextBody {
            get {
                return ResourceManager.GetString("TextBody", resourceCulture);
            }
        }
    }
}
